version: '3.3'

services:
  api:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '4000:2000'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      MONGO_URI: mongodb://mongodb:27017/chatAppMitrain
      DATABASE_URL: mysql://root:password@mysql:1002/mitraindb
      NODE_ENV: production
    command: node dist/index.js