version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2000:2000'
    environment:
      PORT: 2000
      JWT_SECRET: diuwahiuwahdaiu23133212uihdwa

networks:
  default:
    external: true
    name: proxy

volumes:
  mitrain-db:
