version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2000:2000'
    environment:
      PORT: 2000
      JWT_SECRET: diuwahiuwahdaiu23133212uihdwa

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --port=1002
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mitraindb
    volumes:
      - mitrain-db:/var/lib/mysql
    ports:
      - '1002:1002'

networks:
  default:
    external: true
    name: proxy

volumes:
  mitrain-db:
