name: Node.js CD

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/mitrain
          git pull origin develop

      
